name: Fitness Tracker CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v4


    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Display Node Version
      run: node --version


    - name: Install Application Dependencies
      run: npm install


    - name: Skip Tests
      run: echo "No automated tests available. Skipping test stage."
